version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  reviewers:
    - "VladislavAntonyuk"
  assignees:
      - "VladislavAntonyuk"
  open-pull-requests-limit: 10
  groups:
    Aspire:
      patterns:
      - "Aspire*"
    HotChocolate:
      patterns:
      - "HotChocolate*"
    Microsoft:
      patterns:
      - "Microsoft*"
    MassTransit:
      patterns:
      - "MassTransit*"
    Syncfusion:
      patterns:
      - "Syncfusion*"
    CommunityToolkit:
      patterns:
      - "CommunityToolkit*"
    OpenTelementry:
      patterns:
      - "OpenTelementry*"
    Testcontainers:
      patterns:
      - "Testcontainers*"
    xUnit:
      patterns:
      - "xunit*"
