name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Pack
      run: dotnet pack VladislavAntonyukDotnetTemplates.csproj -p:PackageVersion="4.0.${{github.run_number}}"

    - name: Publish NuGet
      run: dotnet nuget push **/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      if: github.ref == 'refs/heads/main'
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
